### ISSUE TITLE
Dependencies Not installed or updated in the package.json file 

### ISSUE THREAD

**Issue by sagarkattel** [nath-Nipan-2022/react-movie-app#1]
Package like react-redux , and @reduxjs/toolkit is missing in the dependencies of package.json file

**Comment by sagarkattel** [comment]
Also dependencies like react-player and react-lazy-load-image-component is  not updated in dependencies

**Comment by nath-Nipan-2022** [comment]
Forgot to update, thought, would do it at last finishing. Now updated as per your issue. 🙌
